### ISSUE TITLE
Webpack compression

### ISSUE THREAD

**Issue by fmarsoni** [kdex/ws-promise#1]
When using with webpack compression plugin ws-promise doesn't work anymore.
The problem is the constructor.name is used in Instructions and Message to identify the type of instruction but compression changes the constructor name

**Comment by kdex** [comment]
Thanks for reporting this issue!

This should be fixed via 974ab4965cf1ee7e2a29f12b84e84ad64bef175e which has landed in `ws-promise@1.5.4`.
